"""drop skipped_count from upload_batches

Revision ID: 0b73b034d836
Revises: f04fe2ccba24
Create Date: 2026-08-05 09:10:18.906136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b73b034d836'
down_revision: Union[str, None] = 'f04fe2ccba24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_batches', 'skipped_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_batches', sa.Column('skipped_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
