"""add fund tables

Revision ID: 1d7b0e987dd6
Revises: 3eda892b7c22
Create Date: 2026-08-19 13:20:48.175256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7b0e987dd6'
down_revision: Union[str, None] = '3eda892b7c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('master_fund_code', sa.String(length=12), nullable=True),
    sa.Column('is_manage_fund', sa.Boolean(), nullable=False),
    sa.Column('class_str', sa.String(length=20), nullable=True),
    sa.Column('special', sa.Boolean(), nullable=False),
    sa.Column('manage_company', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('custodian', sa.String(length=50), nullable=True),
    sa.Column('lead_dist', sa.String(length=50), nullable=True),
    sa.Column('incept_dt', sa.Date(), nullable=True),
    sa.Column('term_dt', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_fund_code'), 'funds', ['fund_code'], unique=True)
    op.create_index('ix_funds_master_fund_code', 'funds', ['master_fund_code'], unique=False)
    op.create_table('fund_adjusted_navs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('base_dt', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('adj_nav', sa.Numeric(precision=18, scale=12), nullable=True),
    sa.Column('adj_factor', sa.Numeric(precision=15, scale=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'base_dt', name='uq_fund_adj_nav_fund_date')
    )
    op.create_index('ix_fund_adjusted_navs_base_dt', 'fund_adjusted_navs', ['base_dt'], unique=False)
    op.create_table('fund_navs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('base_dt', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tax_base_nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('aum', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'base_dt', name='uq_fund_nav_fund_date')
    )
    op.create_index('ix_fund_navs_base_dt', 'fund_navs', ['base_dt'], unique=False)
    op.create_table('fund_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('period_start_value', sa.Date(), nullable=True),
    sa.Column('period_end_value', sa.Date(), nullable=False),
    sa.Column('settlement_type', sa.String(length=10), nullable=False),
    sa.Column('elapsed_days', sa.BigInteger(), nullable=True),
    sa.Column('inception_principal', sa.BigInteger(), nullable=True),
    sa.Column('nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tax_base_nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('post_settlement_nav', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ex_dividend_dt', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'period_end_value', 'settlement_type', name='uq_fund_settlement_fund_period_type')
    )
    op.create_index('ix_fund_settlements_ex_dividend_dt', 'fund_settlements', ['ex_dividend_dt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fund_settlements_ex_dividend_dt', table_name='fund_settlements')
    op.drop_table('fund_settlements')
    op.drop_index('ix_fund_navs_base_dt', table_name='fund_navs')
    op.drop_table('fund_navs')
    op.drop_index('ix_fund_adjusted_navs_base_dt', table_name='fund_adjusted_navs')
    op.drop_table('fund_adjusted_navs')
    op.drop_index('ix_funds_master_fund_code', table_name='funds')
    op.drop_index(op.f('ix_funds_fund_code'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
