"""add market_holidays table

Revision ID: 22963b9f46e4
Revises: 11c30aa5f052
Create Date: 2026-08-05 16:58:49.707903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22963b9f46e4'
down_revision: Union[str, None] = '11c30aa5f052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_holidays',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_holidays')
    # ### end Alembic commands ###
