"""init schema

Revision ID: 3cc48c6557f9
Revises: 
Create Date: 2026-08-04 19:00:26.622968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc48c6557f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_ticker'), 'instruments', ['ticker'], unique=True)
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_name', 'date', name='uq_macro_indicator_name_date')
    )
    op.create_index(op.f('ix_macro_indicators_indicator_name'), 'macro_indicators', ['indicator_name'], unique=False)
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'ex_date', name='uq_dividend_instrument_ex_date')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=1), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', 'period', name='uq_price_instrument_date_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('dividends')
    op.drop_table('upload_batches')
    op.drop_index(op.f('ix_macro_indicators_indicator_name'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index(op.f('ix_instruments_ticker'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
