"""add krx_sector, market_cap, investor_trading, short_selling

Revision ID: 51c43de704c4
Revises: d13a993b2681
Create Date: 2026-08-06 12:00:57.879304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c43de704c4'
down_revision: Union[str, None] = 'd13a993b2681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_trading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('investor_type', sa.String(length=16), nullable=False),
    sa.Column('sell_volume', sa.BigInteger(), nullable=True),
    sa.Column('buy_volume', sa.BigInteger(), nullable=True),
    sa.Column('net_volume', sa.BigInteger(), nullable=True),
    sa.Column('sell_value', sa.BigInteger(), nullable=True),
    sa.Column('buy_value', sa.BigInteger(), nullable=True),
    sa.Column('net_value', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', 'investor_type', name='uq_investor_trading_instrument_date_type')
    )
    op.create_table('short_selling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('short_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_volume', sa.BigInteger(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('short_value', sa.BigInteger(), nullable=True),
    sa.Column('total_value', sa.BigInteger(), nullable=True),
    sa.Column('value_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', name='uq_short_selling_instrument_date')
    )
    op.add_column('instruments', sa.Column('krx_sector', sa.String(length=64), nullable=True))
    op.add_column('prices', sa.Column('market_cap', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'market_cap')
    op.drop_column('instruments', 'krx_sector')
    op.drop_table('short_selling')
    op.drop_table('investor_trading')
    # ### end Alembic commands ###
