"""add corporate_action_events table

Revision ID: 746b364694ab
Revises: fc7c11bfb900
Create Date: 2026-08-06 14:22:56.054397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746b364694ab'
down_revision: Union[str, None] = 'fc7c11bfb900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_action_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('last_data_date', sa.Date(), nullable=False),
    sa.Column('successor_instrument_id', sa.Integer(), nullable=True),
    sa.Column('exchange_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('disposal_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporate_action_events')
    # ### end Alembic commands ###
