"""add sector and industry to instruments

Revision ID: 996eb0352e74
Revises: 22963b9f46e4
Create Date: 2026-08-06 08:57:15.681964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996eb0352e74'
down_revision: Union[str, None] = '22963b9f46e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('sector', sa.String(length=64), nullable=True))
    op.add_column('instruments', sa.Column('industry', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'industry')
    op.drop_column('instruments', 'sector')
    # ### end Alembic commands ###
