"""add shares_outstanding and dividend_adjusted_prices

Revision ID: ab7b6459d6ec
Revises: f98398806524
Create Date: 2026-08-05 14:21:13.801823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7b6459d6ec'
down_revision: Union[str, None] = 'f98398806524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_adjusted_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=1), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', 'period', name='uq_div_adj_price_instrument_date_period')
    )
    op.add_column('instruments', sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'shares_outstanding')
    op.drop_table('dividend_adjusted_prices')
    # ### end Alembic commands ###
