"""add fund_risk_grades

DART 투자설명서에서 읽은 투자위험등급 캐시. 접수번호(rcept_no)가 캐시 키다 —
같은 접수건이면 다시 읽지 않고 새 공시가 뜨면 갱신한다.

Revision ID: cd272b86b40d
Revises: a71c4e08d3b2
Create Date: 2026-08-20 17:16:34.693633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cd272b86b40d'
down_revision: Union[str, None] = 'a71c4e08d3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_risk_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_code', sa.String(length=12), nullable=False),
    sa.Column('risk_grade', sa.Integer(), nullable=True),
    sa.Column('risk_label', sa.String(length=40), nullable=True),
    sa.Column('rcept_no', sa.String(length=14), nullable=True),
    sa.Column('rcept_dt', sa.Date(), nullable=True),
    sa.Column('report_nm', sa.String(length=300), nullable=True),
    sa.Column('dart_fund_name', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_risk_grades_fund_code'), 'fund_risk_grades', ['fund_code'], unique=True)
    op.create_index(op.f('ix_fund_risk_grades_rcept_no'), 'fund_risk_grades', ['rcept_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_risk_grades_rcept_no'), table_name='fund_risk_grades')
    op.drop_index(op.f('ix_fund_risk_grades_fund_code'), table_name='fund_risk_grades')
    op.drop_table('fund_risk_grades')
    # ### end Alembic commands ###
