"""add skipped_count to upload_batches

Revision ID: f04fe2ccba24
Revises: 3cc48c6557f9
Create Date: 2026-08-05 08:47:20.168156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04fe2ccba24'
down_revision: Union[str, None] = '3cc48c6557f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'upload_batches',
        sa.Column('skipped_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_batches', 'skipped_count')
    # ### end Alembic commands ###
