"""add index_memberships table

Revision ID: f98398806524
Revises: 0b73b034d836
Create Date: 2026-08-05 13:34:33.276825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98398806524'
down_revision: Union[str, None] = '0b73b034d836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'as_of_date', 'instrument_id', name='uq_index_membership_name_date_instrument')
    )
    op.create_index('ix_index_membership_name_date', 'index_memberships', ['index_name', 'as_of_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_membership_name_date', table_name='index_memberships')
    op.drop_table('index_memberships')
    # ### end Alembic commands ###
