"""add index_market_caps table

Revision ID: fc7c11bfb900
Revises: 51c43de704c4
Create Date: 2026-08-06 12:56:59.661782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7c11bfb900'
down_revision: Union[str, None] = '51c43de704c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_market_caps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trading_value', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'as_of_date', 'instrument_id', name='uq_index_market_cap_name_date_instrument')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_market_caps')
    # ### end Alembic commands ###
